AllCops:
  Exclude:
    - 'vendor/**/*'
  DisplayCopNames: true
  DisplayStyleGuide: true

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - 'lib/outbox-twilio.rb'

Layout/LineLength:
  IgnoreCopDirectives: true
  Max: 100
